using System.Collections.Generic;
using Newtonsoft.Json;

namespace PartyBot.DataStructs
{
    public class Playlist
    {
        // Creator of the playlist.
        [JsonProperty("Author")]
        public string Author { get; set; }

        // Setting to indicate if this is a private playlist
        [JsonProperty("Private")]
        public bool Private { get; set; }

        // This is a setting for private playlists. Toggles whether other people can view the contents of the playlist.
        [JsonProperty("Viewable")]
        public bool Viewable { get; set; }

        // Just tells if the playlist was autogenerated or not
        [JsonProperty("AutomaticallyGenerated")]
        public bool AutomaticallyGenerated { get; set; }

        // A dictionary with songkeys for keys and the printed out version of songs for values.
        [JsonProperty("Songs")]
        public Dictionary<string, string> Songs { get; set; }

        public Playlist()
        {
            Author = "public";
            Private = false;
            Songs = new Dictionary<string, string>();
            Viewable = true;
        }
        public Playlist(string a, Dictionary<string, string> dict)
        {
            Author = a;
            Private = false;
            Songs = dict;
            Viewable = true;
            AutomaticallyGenerated = false;
        }
        public Playlist(string a, Dictionary<string, string> dict, bool p)
        {
            Author = a;
            Songs = dict;
            Private = p;
        }
        public Playlist(string a, Dictionary<string, string> dict, bool view, bool p)
        {
            Author = a;
            Private = p;
            Songs = dict;
            Viewable = view;
        }
    }
}